### ISSUE TITLE
"TypeError: browser.saveScreen is not a function" if try to run tests on Saucelabs

### ISSUE THREAD

**Issue by idem7x** [webdriverio/visual-testing#124]
**Environment (please complete the following information):**
 - Node.js version: [18.16.0]
 - NPM version: [9.5.1]
 - Browser name and version: [Chrome 114]
 - Platform name and version: [Windows 10]
 - WebdriverIO version: [8.11.2]
 - wdio-image-comparison-service version: [5.0.3]

**Config of WebdriverIO + wdio-image-comparison-service**
```
[
        'image-comparison',
        // The options
        {
            // Some options, see the docs for more
            baselineFolder: join(
                process.cwd(),
                './tests/sauceLabsBaseline/'
            ),
            formatImageName: '{tag}-{logName}-{width}x{height}',
            screenshotPath: join(process.cwd(), '.tmp/'),
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true
        },
    ]
```

**Describe the bug**
```
import LoginPage from '../pageobjects/login.page';
import SecurePage from '../pageobjects/secure.page';

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();

        await LoginPage.login('tomsmith', 'SuperSecretPassword!');
        await expect(SecurePage.flashAlert).toBeExisting();
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!');

        await browser.saveScreen('examplePaged', {
            /* some options */
        })
    });
});
```

If I run this test locally - it passes. If I run it on Saucelabs, I get `**TypeError: browser.saveScreen is not a function**`.

**To Reproduce**
To reproduce bug clone **https://github.com/idem7x/wdiosauce.git** and follow instructions in README. 

**Expected behaviour**
No error appears, screenshot is added. 

**Log**
```
[0-0] 2023-06-16T12:33:51.705Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/aba2c70a593f499a96c2adebe04b5eb6/execute/sync
[0-0] 2023-06-16T12:33:51.705Z INFO webdriver: DATA {
[0-0]   script: 'sauce:context=TypeError: browser.saveScreen is not a function',
[0-0]   args: []
[0-0] }
```

**Comment by wswebcreation** [comment]
This is related to mixed configs. Can you please share all your configs and the order which you import them?

**Comment by wswebcreation** [comment]
@wbigno 

Why do you have this in your sauce config

```js
        [
            ('image-comparison',
            {
                baselineFolder: join(process.cwd(), `visual-regression/${process.env.DOM_BUILD_ENV}/`),
                formatImageName: '{browserName}--{browserVersion}-{tag}',
                screenshotPath: join(process.cwd(), `tmp/${process.env.DOM_BUILD_ENV}/`),
                misMatchTolerance: 0.05,
                savePerInstance: true,
                autoSaveBaseline: true,
                blockOutStatusBar: true,
                blockOutToolBar: true,
                autoElementScroll: false,
                fullPageScrollTimeout: '5000',
                disableCSSAnimation: true
            })
        ],
```

Meaning , why is it between `()`?

**Comment by wbigno** [comment]
Im overriding the services config from my wdio.config. My wdio has image compare, timeline report and dev tools. For sauce I need sauce service, don’t need debtools.. so I have always imported the wdio and then set the services to what I need only for that config. Does that answer your question? Is that not what you would recommend? We have been using this approach for 3 years since v4 of webdriverio. On Dec 30, 2023, at 11:08 PM, Wim Selles ***@***.***> wrote:﻿
@wbigno
Why do you have this in your sauce config
        [
            ('image-comparison',
            {
                baselineFolder: join(process.cwd(), `visual-regression/${process.env.DOM_BUILD_ENV}/`),
                formatImageName: '{browserName}--{browserVersion}-{tag}',
                screenshotPath: join(process.cwd(), `tmp/${process.env.DOM_BUILD_ENV}/`),
                misMatchTolerance: 0.05,
                savePerInstance: true,
                autoSaveBaseline: true,
                blockOutStatusBar: true,
                blockOutToolBar: true,
                autoElementScroll: false,
                fullPageScrollTimeout: '5000',
                disableCSSAnimation: true
            })
        ],
Meaning , why is it between ()?

**Comment by wswebcreation** [comment]
I don't mind that you overwrite it, but please use the correct syntax, you have the `()` which is not needed, change it to this

```js
    services: [
        [
            'sauce',
            {
                sauceConnect: true,
                sauceConnectOpts: {
                    proxyTunnel: true,
                    proxy: 'zproxy.*******.com:9480',
                    pac: 'http://pac.zscaler.net/*******.com/proxy.pac',
                    tunnelCainfo: localCaInfo,
                    logger: async function (message) {
                        console.log(message);
                    }
                },
                setJobNameInBeforeSuite: true
            }
        ],
        [
            'image-comparison',
            {
                baselineFolder: join(process.cwd(), `visual-regression/${process.env.DOM_BUILD_ENV}/`),
                formatImageName: '{browserName}--{browserVersion}-{tag}',
                screenshotPath: join(process.cwd(), `tmp/${process.env.DOM_BUILD_ENV}/`),
                misMatchTolerance: 0.05,
                savePerInstance: true,
                autoSaveBaseline: true,
                blockOutStatusBar: true,
                blockOutToolBar: true,
                autoElementScroll: false,
                fullPageScrollTimeout: '5000',
                disableCSSAnimation: true
            }
        ],
        [TimelineService]
    ],
```
