### ISSUE TITLE
checkFullPageScreen is broken in @wdio/visual-service when using Android in Browserstack

### ISSUE THREAD

**Issue by BosseKarat** [webdriverio/visual-testing#193]
**Environment (please complete the following information):**
 - Node.js version: 18.x

**Config of WebdriverIO + `@wdio/visual-service`**

- "@wdio/visual-service": "1.0.0",
- @wdio/browserstack-service": "^8.27.1"
- @wdio/cli": "^8.27.1
- "typescript": "^5.3.3",

**Describe the bug**
When using any android version along with Chrome in Browserstack, checkFullPageScreen isn't working. It doesn't scroll to capture the entire screen. If I switch back to 'wdio-image-comparison-service', the tool is scrolling and I'm able to capture the entire screen. 

**To Reproduce**
Use the following capabilities along with Browserstack to launch your tests in a Android/Chrome emulation

`var capabilities = {
 "browserName" : "chrome",
 'bstack:options' : {
   "osVersion" : "12.0",
   "deviceName" : "Samsung Galaxy S21",
 }
}`

Try to capture an entire page where scrolling is required using checkFullPageScreen, e.g https://webdriver.io/docs/sponsor

Look at the baseline and note that the enitre page wasn't captured, only the part that was visible in the viewport. 

Switch from "@wdio/visual-service" to 'wdio-image-comparison-service' and run the same tests again. The baseline should now contain the entire page. 

**Expected behavior**

checkFullPageScreen should capture the entire page for Android/Chrome using browserstack.

**Log**
This issue doesn't provide any logs but if it helps I can provide it.

**Comment by wswebcreation** [comment]
Hi @BosseKarat 
Thanks for filing an issue, that is really strange, I need to dive into it. Can you also provide your config so I  can replicate this. I need to check if I also have a BS account, otherwise, I'll request one to try this out

**Comment by BosseKarat** [comment]
> Hi @BosseKarat Thanks for filing an issue, that is really strange, I need to dive into it. Can you also provide your config so I can replicate this. I need to check if I also have a BS account, otherwise, I'll request one to try this out

I´ll try to upload a reproducible example on git later today for you Will. You will need your own login credentials though. Browserstack allows you to sign up for a trial but I'm not sure if that will give you enough time to test this thoroughly. Perhaps @christian-bromann can help you out with that with the new partnership https://webdriver.io/blog/2024/01/29/browserstack-partnership :)

**Comment by BosseKarat** [comment]
@wswebcreation - Clone this repo, don't forget to add your browserstack credentials https://github.com/BosseKarat/wdio-browserstack.git

**Comment by wswebcreation** [comment]
Sorry for the late reply, I requested a licence and will check it when I have it

**Comment by BosseKarat** [comment]
No worries @wswebcreation - Let me know if there is anything I can do to assist you.

**Comment by BosseKarat** [comment]
@wswebcreation - Believe it or not but this seems to have been fixed in @wdio/visual-service@2.0.0. I ran the same tests again after updating from 1.0.0 to @latest and everything seems to be working as expected. You can close this issue unless you want to try it out yourself.

**Comment by wswebcreation** [comment]
Ahh, cool, then I'll close this one, thanks for getting back on this
