### ISSUE TITLE
custom commands for visual testing not getting registered

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/visual-testing#200]
**Environment (please complete the following information):**
 - Node.js version: v20
 - NPM version: latest
 - Browser name and version: Mobile Safari
 - Platform name and version: Mac
 - WebdriverIO version: Latest
 - `@wdio/visual-service` version: Latest

**Config of WebdriverIO + `@wdio/visual-service`**
n/a

**Describe the bug**
I see in our CI pipeline bugs like these:

```
TypeError: browser.checkElement is not a function
    at Context.<anonymous> (file:///home/runner/work/visual-testing/visual-testing/tests/specs/mobile.web.spec.ts:33:40)
```

Is this expected behavior?

**To Reproduce**
Run a pipeline test, e.g. https://github.com/webdriverio/visual-testing/actions/runs/7833213506/job/21378868166?pr=199#step:9:5605

**Expected behavior**

If we can not support certain methods we should provide a better error message, telling why it is not supported and pointing to an open issue or something.

**Log**
see link above.

**Additional context**

**Comment by wswebcreation** [comment]
Hmm, this is not what should happen, will look into it

**Comment by wswebcreation** [comment]
Hi @christian-bromann 

I've been looking into this and I haven't found the problem yet, but also haven't seen this with newer runs. 

The only thing I saw was:
- only in our pipeline
- it only happens with Simulators but not consistently 

Going to close it for now
