### ISSUE TITLE
savePerInstance doesn't set the correct name to the folder when using Browserstack

### ISSUE THREAD

**Issue by BosseKarat** [webdriverio/visual-testing#216]
**Environment (please complete the following information):**
 - Node.js version: 18.X

 - Browser name and version: Android -> Chrome 
 - WebdriverIO version: 8.32.1
 - `@wdio/visual-service` version: @4.0.2

**Config of WebdriverIO + `@wdio/visual-service`**

Capabilities when using Browserstack: 

```
  capabilities: [
    {
      browserName: 'chrome',
      'bstack:options': {
        deviceName: 'Samsung Galaxy S22',
        osVersion: '12.0'
      }
    },]
```

**Describe the bug**

The folder created for Android baseline images doesn't have the correct name: 

![bild](https://github.com/webdriverio/visual-testing/assets/86266759/5ffb6cbb-7fe9-4083-a542-eafbc0a9ff2b)

**To Reproduce**

Use the capabilities listed above and Browserstack. Set savePerInstance  to true

**Expected behavior**
Setting the folder name to "rfcn20sf4nf" for Android devices is obviously not correct. It should follow the same pattern as the other devices. 

**Log**

console.log(browser) outputs: 

> Browser {
> [1] [0-0]   sessionId: 'xxx',
> [1] [0-0]   capabilities: {
> [1] [0-0]     platform: 'LINUX',
> [1] [0-0]     webStorageEnabled: false,
> [1] [0-0]     takesScreenshot: true,
> [1] [0-0]     javascriptEnabled: true,
> [1] [0-0]     databaseEnabled: false,
> [1] [0-0]     networkConnectionEnabled: true,
> [1] [0-0]     locationContextEnabled: false,
> [1] [0-0]     warnings: {},
> [1] [0-0]     desired: {
> [1] [0-0]       'goog:chromeOptions': [Object],
> [1] [0-0]       platformName: 'Android',
> [1] [0-0]       browserName: 'chrome',
> [1] [0-0]       newCommandTimeout: 0,
> [1] [0-0]       deviceName: 'android',
> [1] [0-0]       systemPort: 8202,
> [1] [0-0]       udid: 'RFCN20RCL7D',
> [1] [0-0]       chromedriverPort: 18082,
> [1] [0-0]       skipServerInstallation: true
> [1] [0-0]     },
> [1] [0-0]     'goog:chromeOptions': { args: [Array] },
> [1] [0-0]     platformName: 'Android',
> [1] [0-0]     browserName: 'chrome',
> [1] [0-0]     newCommandTimeout: 0,
> [1] [0-0]     deviceName: 'RFCN20RCL7D',
> [1] [0-0]     systemPort: 8202,
> [1] [0-0]     udid: 'RFCN20RCL7D',
> [1] [0-0]     chromedriverPort: 18082,
> [1] [0-0]     skipServerInstallation: true,
> [1] [0-0]     appPackage: 'com.android.chrome',
> [1] [0-0]     appActivity: 'com.google.android.apps.chrome.Main',
> [1] [0-0]     deviceUDID: 'RFCN20RCL7D',
> [1] [0-0]     deviceApiLevel: 29,
> [1] [0-0]     platformVersion: '10',
> [1] [0-0]     deviceScreenSize: '1080x2400',
> [1] [0-0]     deviceScreenDensity: 480,
> [1] [0-0]     deviceModel: 'SM-G981B',
> [1] [0-0]     deviceManufacturer: 'samsung',
> [1] [0-0]     pixelRatio: 3,
> [1] [0-0]     statBarHeight: 77,
> [1] [0-0]     viewportRect: { left: 0, top: 77, width: 1080, height: 2101 }
> [1] [0-0]   },
> [1] [0-0]   addCommand: [Function (anonymous)],
> [1] [0-0]   overwriteCommand: [Function (anonymous)],
> [1] [0-0]   addLocatorStrategy: [Function (anonymous)],
> [1] [0-0]   getAccessibilityResultsSummary: [AsyncFunction (anonymous)],
> [1] [0-0]   getAccessibilityResults: [AsyncFunction (anonymous)]
> [1] [0-0] }

**Additional context**

**Comment by BosseKarat** [comment]
n00b question @wswebcreation - Since I have a BS account I might be able to fix this myself with a 'little' bit help from you. I'm just wondering if there's a way to import my fork into my project using e.g npm link or something similar.

**Comment by wswebcreation** [comment]
Hi @BosseKarat 

Yes, you should be able to do that, but I just create a fix for it 😅 , see https://github.com/webdriverio/visual-testing/pull/217

**Comment by BosseKarat** [comment]
> Hi @BosseKarat 
> 
> Yes, you should be able to do that, but I just create a fix for it 😅 , see https://github.com/webdriverio/visual-testing/pull/217

Looking at your PR I'm thankful you did 😂

**Comment by BosseKarat** [comment]
I don't know if you still don't have a BS account but I tested the fix this morning and it's working like a charm. Nice work 🥳 

![bild](https://github.com/webdriverio/visual-testing/assets/86266759/19cd6de5-b95a-4a77-a7b9-e7d02ca9b980)

**Comment by wswebcreation** [comment]
Awesome, thanks for the confirmation
