### ISSUE TITLE
Error in azure-devops while initialising the service

### ISSUE THREAD

**Issue by lavanyalaguduva** [webdriverio/visual-testing#31]
> **NOTE: Be aware of the fact that this module is only a plugin that provides all functionality from [`webdriver-image-comparison`](https://github.com/wswebcreation/webdriver-image-comparison). So please check if this is an issue with this plugin or with `webdriver-image-comparison`.**

**Environment (please complete the following information):**
 - Node.js version: v10.17.0
 - NPM version: 6.11.3
 - Browser name and version: Chrome V 80(but this issue is independent of browsers)
 - Platform name and version: Azure devops using kubernates pool
 - WebdriverIO version: 5.15.6
 - wdio-image-comparison-service version: 1.12.2

**Config of WebdriverIO + wdio-image-comparison-service**
**image-comparison.conf.js**
```
const path = require('path');
const BASE_PATH = path.join(__dirname, '..');
const OUTPUT_PATH = `${BASE_PATH}/output`;

function getImageComparisonServiceConfig() {
  return [
    'image-comparison',
    {
      baselineFolder: path.join(OUTPUT_PATH, 'screenshots/reference'),
      formatImageName: '{tag}_{width}x{height}',
      screenshotPath: path.join(OUTPUT_PATH, 'screenshots/screen'),
      clearRuntimeFolder: true,
      savePerInstance: false,
      autoSaveBaseline: true,
      blockOutStatusBar: true,
      blockOutToolBar: true,
      disableCSSAnimation: true,
    },
  ];
}

module.exports = { getImageComparisonServiceConfig };
```

**browserstack.conf.js**
```
const browserstack = require('browserstack-local');
const { getImageComparisonServiceConfig } = require('./visual-regression.conf');

const { LOCAL_IDENTIFIER, APPLICATION_URL } = require('../env');
// have main config file as default but overwrite environment specific information
exports.config = {
  ...require('./wdio.conf').config,

  services: ['browserstack', getImageComparisonServiceConfig()],
.....
.....
....
}
```

**Describe the bug**
When I run the tests in azure devops pipeline using kubernates pool, I get the following error
`ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: libuuid.so.1: cannot open shared object file: No such file or directory`

**Comment by wswebcreation** [comment]
Closing this one due to inactivity
