### ISSUE TITLE
Visual-service is getting the wrong type in service.js beforetest hook

### ISSUE THREAD

**Issue by siajangani** [webdriverio/visual-testing#322]
Hi,

Running the latest Wdio on my local project and we are using "@wdio/visual-service": 4.1.1.
all the tests are passing and the image compare is also working but getting thrown a type exception in
node_modules\@wdio\visual-service\dist\service.js file in beforeTest hook as it is expecting "filename" not just "file" - line 61
I am guessing this is coming from jasmine-core/jasmine.js spec 
"* @property {String} filename - The name of the file the spec was defined in."

the actual error is below:

![image](https://github.com/webdriverio/visual-testing/assets/61720923/93406ef5-ac63-44e4-97bd-258f5d5fe28c)

 - Node.js version: [18.10.0]
 - NPM version: [8.15.0]
 - Browser name and version: [Chrome 122]
 - Platform name and version: [e.g. Windows 10]
 - WebdriverIO version: [8.35.0]
 - `@wdio/visual-service` version: [4.1.1]

is it just a typo or am I missing something,

I can raise a PR if that is the case.

**Comment by wswebcreation** [comment]
ahhhh, yeah, it might be that we haven't tested this for all framework adapters 😅 . Feel free to raise a PR. Thanks!

**Comment by siajangani** [comment]
@wswebcreation - could you approve/publish please?

**Comment by wswebcreation** [comment]
Will be fixed with this PR https://github.com/webdriverio/visual-testing/pull/323
