### ISSUE TITLE
Error message no longer readable in case of mismatch after update to 6.2.3

### ISSUE THREAD

**Issue by P-Courteille** [webdriverio/visual-testing#679]
**Environment (please complete the following information):**
 - Node.js version: 22.11.0
 - NPM version: 10.9.1
 - Platform name and version: Android 11 (testing on native android app)
 - WebdriverIO version: 9.4.1
 - `@wdio/visual-service` version: 6.2.3
 - `@wdio/mocha-framework` version: 9.2.8
 - `@wdio/local-runner` version: 9.4.1
 - `@wdio/globals` version: 9.4.1
 - `@wdio/cli` version: 9.4.1
 - `Appium` version: 2.11.5
 - `tsx` version: 4.19.2

**Config of WebdriverIO + `@wdio/visual-service`**
```
services: [
        // your other services
        [
            "visual",
            {
                baselineFolder: path.join(process.cwd(), "onboard", "baseline"),
                formatImageName: "{tag}-{width}x{height}-{dpr}",
                screenshotPath: path.join(process.cwd(), "onboard", "output", "visual"),
                savePerInstance: true,
                clearRuntimeFolder: true,
            },
        ],
```

**Describe the bug**
After the update to 6.2.3, something seems to not working as expected in case of mismatch.
![image](https://github.com/user-attachments/assets/659d7697-fe2e-43e8-87d2-0616d9c1f35e)

---
💡Look to be something wrong the output of 'compareResult' (the issue occurs during the processResult step of variable "potentialResult" in or with the parsing of "makeThrowingMatcher".

![image](https://github.com/user-attachments/assets/a9b031b6-d5e5-4ce6-9727-ec77f4b89f89)

---

**Expected behavior**
A readable message like:
'Expected image to match with given asymmetric matcher but did not pass!\n'

**Link:**
Detected after https://github.com/webdriverio/visual-testing/issues/656#issuecomment-2530824970

**Comment by wswebcreation** [comment]
Found the issue, will fix it and release a new version, it will now throw this error

```logs
Error: Instance "androidDevice":
Expected image mismatch percentage to be at most 0%, but was 0.238%.
If this is acceptable, you may need to adjust the threshold or update the baseline image if the changes are intentional.

Baseline: /Users/wimselles/Git/wdio/issues/issue-656/myProject/baseline/pixel_8_pro_android_15_api_35/FullScreen-1344x2992-3.png
Actual Screenshot: /Users/wimselles/Git/wdio/issues/issue-656/myProject/output/visual/actual/pixel_8_pro_android_15_api_35/FullScreen-1344x2992-3.png
Difference: /Users/wimselles/Git/wdio/issues/issue-656/myProject/output/visual/diff/pixel_8_pro_android_15_api_35/FullScreen-1344x2992-3.png

For guidance on handling visual discrepancies, refer to: https://webdriver.io/docs/api/visual-regression.html
```

**Comment by wswebcreation** [comment]
See https://github.com/webdriverio/visual-testing/releases/tag/%40wdio%2Fvisual-service%406.2.4

**Comment by P-Courteille** [comment]
Thanks @wswebcreation, have a nice day
