### ISSUE TITLE
resizeDimensions is not in pixel but in resizeDimensions/devicePixelRatio

### ISSUE THREAD

**Issue by P-Courteille** [webdriverio/visual-testing#680]
**Environment (please complete the following information):**
 - Node.js version: 22.11.0
 - NPM version: 10.9.1
 - Platform name and version: Android 11 (testing on native android app)
 - WebdriverIO version: 9.4.1
 - `@wdio/visual-service` version: 6.2.3
 - `@wdio/mocha-framework` version: 9.2.8
 - `@wdio/local-runner` version: 9.4.1
 - `@wdio/globals` version: 9.4.1
 - `@wdio/cli` version: 9.4.1
 - `Appium` version: 2.11.5
 - `tsx` version: 4.19.2

**Config of WebdriverIO + `@wdio/visual-service`**
```
services: [
        // your other services
        [
            "visual",
            {
                baselineFolder: path.join(process.cwd(), "onboard", "baseline"),
                formatImageName: "{tag}-{width}x{height}-{dpr}",
                screenshotPath: path.join(process.cwd(), "onboard", "output", "visual"),
                savePerInstance: true,
                clearRuntimeFolder: true,
            },
        ],
```

**Describe the bug**
According to the [documentation ](https://webdriver.io/docs/visual-testing/method-options/#resizedimensions), resizeDimensions is suppose to be in pixel but according to the code and the behavior, the pixel are divided by devicePixelRatio:
![image](https://github.com/user-attachments/assets/bf9fe99c-2901-4bea-a3fd-fb2434bd63f3)

* In my example, the element is 96*96px with a dpr to 2:
   * With 'bottom: -18', the baseline is $${\color{red}87}$$ instead of $${\color{green}78}$$
   * With 'bottom: -19', the baseline is $${\color{red}87}$$ instead of $${\color{green}77}$$
   * With 'bottom: -25', the baseline is $${\color{red}84}$$ instead of $${\color{green}71}$$

---

**Expected behavior**

Option 1: remove the division by devicePixelRatio (or apply it in specific condition if it was needed in some situation)
Option 2: update the documentation to give this information

---
💡The documentation could be update to precise that resizeDimensions is not only to "cutout bigger" but cutout bigger or smaller.

**Comment by wswebcreation** [comment]
Thanks for pointing this out. I made an error here and fixed it with this PR https://github.com/webdriverio/visual-testing/pull/684

**Comment by wswebcreation** [comment]
released https://github.com/webdriverio/visual-testing/releases/tag/%40wdio%2Fvisual-service%406.2.5

**Comment by P-Courteille** [comment]
Thanks, have a nice day
