### ISSUE TITLE
Failed to execute visual testing in mobile native app with "appium:options" caps

### ISSUE THREAD

**Issue by Dinh246** [webdriverio/visual-testing#692]
**Environment (please complete the following information):**
 - Node.js version: v22.12.0
 - NPM version: 10.9.0
 - Browser name and version: [e.g. Chrome 68]
 - Platform name and version: MacOS 15.2
 - WebdriverIO version: 9.4.5
 - `@wdio/visual-service` version: 6.2.5
**Config of WebdriverIO + `@wdio/visual-service`**
An example of how you configured the `@wdio/visual-service`
capabilities: [
    {
      // capabilities for local Appium web tests on an Android Emulator
      platformName: "Android",
      //   browserName: "Chrome",
      "appium:automationName": "UiAutomator2",
      "appium:options": {
        udid: "emulator-5554",
        app: "app/app.apk",
        fullReset: true
      },
      port: 4724,
    },
  ],

**Describe the bug**
The visual testing run into an error if user used capabilities that have "appium:options"

**To Reproduce**

use the capabilities like above and run visual testing

**Expected behavior**
The test should run without any issues

**Log**
[0-0] unknown method in "Onboarding voice changer app.should onboarding successfully and open home screen"
unknown method: WebDriverError: Method is not implemented when running "execute/sync" with method "POST" and args "function hideScrollBars(hide) {
    try {
        document.body.style.overflow = hide ? 'hidden' : '';
    }
    catch (_e) {
        // Do nothing
    }
}"
    at async beforeScreenshot (file:///Users/truongdinh/Appium/AzureAutopilot/node_modules/webdriver-image-comparison/dist/helpers/beforeScreenshot.js:36:9)
    at async saveWebElement (file:///Users/truongdinh/Appium/AzureAutopilot/node_modules/webdriver-image-comparison/dist/commands/saveWebElement.js:44:34)
    at async checkWebElement (file:///Users/truongdinh/Appium/AzureAutopilot/node_modules/webdriver-image-comparison/dist/commands/checkWebElement.js:22:57)

**Additional context**

**Comment by wswebcreation** [comment]
Thanks, this will be fixed with this PR https://github.com/webdriverio/visual-testing/pull/688

**Comment by wswebcreation** [comment]
@Dinh246 

It's fixed in version [`6.3.0`](https://github.com/webdriverio/visual-testing/releases/tag/%40wdio%2Fvisual-service%406.3.0)
