### ISSUE TITLE
Chrome Devtools support is broken

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/visual-testing#97]
See https://github.com/wswebcreation/webdriver-image-comparison/issues/115

**Comment by christian-bromann** [comment]
With support for driver management in WebdriverIO I started to discourage people of using `devtools` as automation protocol. It was useful when we haven't had driver management built-in. Now it doesn't make much sense anymore. Therefore I suggest to close this as `won't-do`.

**Comment by wswebcreation** [comment]
Ok, thanks, will remove it in a PR
